EXTRA_CFLAGS = -D Special_IsPokerusInParty=$(Special_IsPokerusInParty) -D CHANCE_REDUCE_POKERUS_128_STEPS=$(CHANCE_REDUCE_POKERUS_128_STEPS)

EXTRA_ARMIPS_FLAGS = -equ Special_IsPokerusInParty $(Special_IsPokerusInParty) -equ CHANCE_REDUCE_POKERUS_128_STEPS $(CHANCE_REDUCE_POKERUS_128_STEPS)
