GetMonData              = 0x0803FBE8 |1;
SetMonData              = 0x0804037C |1;
AdjustFriendship        = 0x080436F8 |1;
CheckPartyPokerus       = 0x08043A70 |1;
CheckPartyHasHadPokerus = 0x08043AD8 |1;
Random                  = 0x08044EC8 |1;
GetVarPointer           = 0x0806E454 |1;
__umodsi3               = 0x081E4684 |1;

/* -------------------------------------------------------------------------- */

gPlayerParty            = 0x02024284;

gBitTable               = 0x0825E45C;
